### ISSUE TITLE
IT and Politik seems to look like same tag

### ISSUE THREAD

**Issue by RogerSik** [SSilence/selfoss#677]
![2015-06-25 16_42_08-selfoss 30](https://cloud.githubusercontent.com/assets/165814/8357064/2b328a08-1b59-11e5-937d-1b8e06c35a70.png)

Hello in the screenshot you see that IT are 20 unread items and in Politik are 21 unread items.

But when you search through these two tags then you see that in IT are only 1 unread items and in Politik are 20 unread items.

These sites arent tagged as politik and it. There only it or politik. 

I think because of the letter IT in Pol**it**ik they get recognized as IT.

**Comment by niol** [comment]
Which version are you using? Which database backend?

**Comment by RogerSik** [comment]
Hi niol,

Version 2.13 and database sqlite.

**Comment by jtojnar** [comment]
I believe this was fixed in #668

**Comment by RogerSik** [comment]
Verification that the newest version is used.
![2015-06-26 06_40_40-](https://cloud.githubusercontent.com/assets/165814/8370856/9f65d73e-1bce-11e5-8392-453d7267c3aa.png)

**Comment by niol** [comment]
Then this can be closed.

**Comment by RogerSik** [comment]
The Problem still exists. I wanted only show that I really have the newest version.
________________________________
Von: niol<mailto:notifications@github.com>
Gesendet: ‎26.‎06.‎2015 07:44
An: SSilence/selfoss<mailto:selfoss@noreply.github.com>
Cc: Roger Sikorski<mailto:roger@sikorski.cc>
Betreff: Re: [selfoss] IT and Politik seems to look like same tag (#677)


Then this can be closed.

**Comment by niol** [comment]
This is fixed in the development version (unreleased).

**Comment by RogerSik** [comment]
I close this ticket because in 2.14 this problem doenst appear more.
